### ISSUE TITLE
ewindisch/dockenstack start failures

### ISSUE THREAD

**Issue by kfox1111** [ewindisch/dockenstack#1]
The container is not starting due to /usr/local/bin/start not existing. After a bit of poking, manually starting it with /opt/dockenstack/bin/start allowed it to make progress.

Then its failing to start with:
docker run -privileged -lxc-conf=aa_profile=unconfined -t -i ewindisch/dockenstack /opt/dockenstack/bin/start
WARNING: WARNING: Docker detected local DNS server on resolv.conf. Using default external servers: [8.8.8.8 8.8.4.4]
- Starting message broker rabbitmq-server                                                        140210 20:13:01 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
  140210 20:13:01 mysqld_safe Logging to '/var/log/mysql/error.log'.
  140210 20:13:01 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
                                                                                         [ OK ]
  2014/02/10 20:13:05 socat[617] E connect(3, AF=1 "/var/run/docker.sock", 22): No such file or directory
  [/var/lib/docker|60b62457] +job initserver()
  [/var/lib/docker|60b62457.initserver()] Creating server
  [/var/lib/docker|60b62457] +job init_networkdriver()
  [/var/lib/docker|60b62457.init_networkdriver()] creating new bridge for docker0
  [/var/lib/docker|60b62457.init_networkdriver()] getting iface addr
  [/var/lib/docker|60b62457] -job init_networkdriver() = OK (0)
  2014/02/10 20:13:06 WARNING: Your kernel does not support cgroup swap limit.
  [/var/lib/docker|60b62457.initserver()] Creating pidfile
  [/var/lib/docker|60b62457.initserver()] Setting up signal traps
  [/var/lib/docker|60b62457] -job initserver() = OK (0)
  [/var/lib/docker|60b62457] +job serveapi(unix:///var/run/docker.sock)
  2014/02/10 20:13:06 Listening for HTTP on unix (/var/run/docker.sock)
  2014/02/10 20:13:06 GET /v1.3/version
  [/var/lib/docker|60b62457] +job version()
  [/var/lib/docker|60b62457] -job version() = OK (0)
  2014/02/10 20:13:06 GET /v1.9/images/json?filter=busybox
  [/var/lib/docker|60b62457] +job images()
  [/var/lib/docker|60b62457] -job images() = OK (0)
  2014/02/10 20:13:06 POST /v1.9/images/load
  [/var/lib/docker|60b62457] +job load()
  [error] mount.go:11 [warning]: couldn't run auplink before unmount: exit status 22
  Driver aufs failed to get image rootfs bf747efa0e2fa9f7c691588ce3938944c75607a7bb5e757f7369f86904d97c78: invalid argument[/var/lib/docker|60b62457] -job load() = ERR (1)
  [error] api.go:959 Error: load: Driver aufs failed to get image rootfs bf747efa0e2fa9f7c691588ce3938944c75607a7bb5e757f7369f86904d97c78: invalid argument
  [error] api.go:91 HTTP Error: statusCode=500 load: Driver aufs failed to get image rootfs bf747efa0e2fa9f7c691588ce3938944c75607a7bb5e757f7369f86904d97c78: invalid argument
  2014/02/10 20:13:06 Error: load: Driver aufs failed to get image rootfs bf747efa0e2fa9f7c691588ce3938944c75607a7bb5e757f7369f86904d97c78: invalid argument

Docker version 0.8.0, build cc3a8c8
Ubuntu 13.10 x86_64

**Comment by ewindisch** [comment]
Try adding '-v /var/lib/docker' to the command arguments. I've excluded this as it isn't necessary for storage drivers besides AUFS. I thought it would "just work" with AUFS as well, but I might've been wrong.

**Comment by ewindisch** [comment]
I'm now using AUFS locally, so I can verify that dockenstack is working correctly when passing '-v /var/lib/docker'. I'll update the README.

**Comment by timfallmk** [comment]
@ewindisch are you starting docker containers within this container? Docker can't do nesting using AUFS since AUFS trees cannot exist on AUFS trees.

I had to switch to using the devicemapper storage driver to get past this.

**Comment by ewindisch** [comment]
@timfallmk Yes, I'm starting docker containers inside this container. AUFS should work as long as you pass the '-v /var/lib/docker'. Alternatively, you can use AUFS on the host and force another driver inside dockenstack.

**Comment by timfallmk** [comment]
@ewindisch if you specify `-v /var/lib/docker` then, to my understanding, you're not actually using AUFS, but passing a bind-mounted volume to the container.

**Comment by ewindisch** [comment]
@timfallmk Correct. In this case, as long as /var/lib/docker itself is not on an AUFS filesystem, using the bind-mount allows you to use the AUFS driver for Docker-in-Docker.

**Comment by ewindisch** [comment]
The readme had been updated a while back for instructions for AUFS users.
