### ISSUE TITLE
/var/lib/docker/aufs/mnt/$ID is not within /var/lib/docker/aufs/mnt/$ID

### ISSUE THREAD

**Issue by Phi-Ho** [ewindisch/dockenstack#10]
After cloning latest  dockenstack with 'Update to trusty and install kerberos headers' and adding 'RUN apt-get install -q -y python-pip', build still fails with:

Step 35 : RUN chown -R devstack /devstack
 ---> Running in ab674d637aeb
2014/06/27 16:26:39 /var/lib/docker/aufs/mnt/ab674d637aeb10fcbfc223d2be87879dfaa025173a8fa7b7f09d445866921b7c is not within /var/lib/docker/aufs/mnt/ab674d637aeb10fcbfc223d2be87879dfaa025173a8fa7b7f09d445866921b7c

This seems to be fixed with setting WORKDIR to somewhere else, says '/opt':
# Fix /var/lib/docker/aufs/mnt/$ID is not within /var/lib/docker/aufs/mnt/$ID
# WORKDIR /

WORKDIR /opt
# Fix ownership of all files

RUN chown -R devstack /devstack

CMD ["/opt/dockenstack/bin/start"]

**Comment by paulczar** [comment]
this seems to be avoidable by using Docker 1.0

**Comment by ewindisch** [comment]
Noted a requirement on docker 1.0+ in the readme
