### ISSUE TITLE
stack.sh does run on raring.

### ISSUE THREAD

**Issue by timfallmk** [ewindisch/dockenstack#3]
```
WARNING: this script has not been tested on raring
[Call Trace]
/devstack/stack.sh:148:die
[ERROR] /devstack/stack.sh:148 If you wish to run this script anyway run with FORCE=yes
/devstack/functions-common: line 259: /opt/stack/logs/error.log: No such file or directory
```

Running with `FORCE=yes` gives you further errors about running it as root.

**Comment by ewindisch** [comment]
This was working fine at some point. I'm not sure what broke. However, I'll be updating this image to use a newer image... raring is vulnerable to Heartbleed (not, I suppose, too important here... but it's EOL and we should update)

**Comment by ewindisch** [comment]
Updated to saucy
