### ISSUE TITLE
dockenstack local build fails

### ISSUE THREAD

**Issue by Phi-Ho** [ewindisch/dockenstack#7]
After adding python-pip
# Mask python-six because the apt package can conflict with the pypi version.

RUN apt-get remove -q -y python-six
RUN apt-get install -y python-pip

The build failed with:
2014/06/10 23:35:17 The command [/bin/sh -c pip install -r https://raw.github.com/openstack/requirements/master/global-requirements.txt] returned a non-zero code: 1

Please find appended below the tail of the build.

Regards,

PhiHo

...
...
running build
running build_ext
building 'kerberos' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/kerberos.c -o build/temp.linux-x86_64-2.7/src/kerberos.o sh: 1: krb5-config: not found
x86_64-linux-gnu-gcc: error: sh:: No such file or directory
x86_64-linux-gnu-gcc: error: 1:: No such file or directory
x86_64-linux-gnu-gcc: error: krb5-config:: No such file or directory
x86_64-linux-gnu-gcc: error: not: No such file or directory
x86_64-linux-gnu-gcc: error: found: No such file or directory
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/kerberos/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-snR0zm-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/kerberos
Storing debug log for failure in /.pip/pip.log
2014/06/10 23:35:17 The command [/bin/sh -c pip install -r https://raw.github.com/openstack/requirements/master/global-requirements.txt] returned a non-zero code: 1

**Comment by ewindisch** [comment]
This has been fixed. Thank you!

see: https://github.com/ewindisch/dockenstack/commit/737102902cece7650c0e2cf77e53664dc5ca284a
